gText_Birch_Welcome::
	.string "Good morning! Did you sleep well?\p"
	.string "Welcome to the REGIUS ARCHIPELAGO!\p"
	.string "You remember me, don't you?\p"
	.string "I'm your GRANDMA, and you're staying\n"
	.string "with me on GATEWAY ISLAND, my home.\p"
	.string "Today is a very special day!\n"
	.string "Did you forget?\p"
	.string "Oh, but I'm getting ahead of myself.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is a POKéMON.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "These islands are home to lots of\n"
	.string "unique POKéMON.\p"
	.string "Many of them can't be found\n"
	.string "anywhere else in the world!\p"
	.string "The people here live in harmony\n"
	.string "with nature, and have a strong bond\l"
	.string "with their POKéMON.\p"
	.string "The islands of REGIUS are steeped\n"
	.string "in ancient mysteries.\p"
	.string "But before you can go out and\n"
	.string "explore them all, you'll need a\l"
	.string "POKéMON companion of your own.\p"
	.string "You guessed it, didn't you?\p"
	.string "Today is the day you get\n"
	.string "your first POKéMON!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "So… tell me something.$"

gText_Birch_BoyOrGirl::
	.string "How are you feeling today?$"

gText_Birch_WhatsYourName::
	.string "Oho, is that so?\n"
	.string "And what should I call you today?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}{KUN}, huh?\n"
	.string "Ha! I like it.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, {PLAYER}{KUN}, are you ready?\p"
	.string "Your new life on the REGIUS\n"
	.string "ARCHIPELAGO is about to begin!\p"
	.string "A journey of freedom and discovery\n"
	.string "awaits you.\p"
	.string "Let's get started, shall we?\p"
	.string "$"
